# Generated by Django 4.0 on 2022-12-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=200)),
                ('gender', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='api/img/')),
                ('email', models.CharField(default='', max_length=200)),
                ('token', models.CharField(max_length=300)),
                ('fb_token', models.CharField(max_length=200)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
    ]
