# Generated by Django 4.0 on 2022-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField(default=0)),
                ('user2', models.IntegerField(default=0)),
                ('action', models.IntegerField(default=0)),
            ],
        ),
    ]
