# Generated by Django 4.0 on 2022-12-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField(default=0)),
                ('user2', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField()),
                ('reciver_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=800)),
                ('main_chat1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_chat', to='api.main_chat')),
            ],
        ),
    ]
